require('dotenv').config();
const express=require('express');
const app=express();
const cors=require('cors');
app.use(cors());
app.use(express.json());
app.listen(process.env.PORT,()=> console.log("server started"));
const mongoose=require('mongoose');
mongoose.connect(process.env.DB);
mongoose.set('strictQuery',true);
const subRouter=require('./routes/product');
app.use('/product',subRouter);
